Semantic search
r2dl/toto-client pull request #3
Opened 2023-01-23 10:39 UTC by patrickstewartswan

Adding method to execute semantic_search graphql query

2023-01-25 10:28 UTC, patrickstewartswan commented
Test in conjunction with https://github.com/r2dl/toto-sql/pull/40 by running toto/test/test_csheet.py on toto-sql

2023-01-26 12:29 UTC, charlottecrabbr2 approved these changes

2023-01-27 09:41 UTC, lcasassa requested changes

2023-01-27 09:41 UTC, lcasassa commented on toto_client/toto_client.py
> +        self, search_term: str, num_results: Optional[Union[str, int]] = None
why num_restults can be a str?? should it be only an int?

2023-02-13 16:56 UTC, merged